apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stoat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Clusterforgers/k3s-cluster-manifests.git'
    targetRevision: HEAD
    path: apps/stoat
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stoat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
