apiVersion: v2
name: nextcloud
description: Helm chart for Nextcloud
type: application
version: 0.1.0
dependencies:
  - name: nextcloud
    repository: https://nextcloud.github.io/helm/
    version: "9.3.0"
